export const policyReviewerLaunchPolicy = {
  cli: 'codex-cli/0.147.0',
  executable: 'codex',
  subcommand: 'exec',
  model: 'gpt-5.6-terra',
  reasoningConfig: 'model_reasoning_effort=high',
  flags: [
    '--model',
    '--config',
    '--ephemeral',
    '--ignore-user-config',
    '--sandbox',
    '--cd',
    '--output-schema',
    '--output-last-message',
  ],
  sandbox: 'read-only',
  outerExecutable: 'sandbox-exec',
  outerProfileFlag: '-f',
  clearedEnvironment: true,
  detachedProcessGroup: true,
  permitToolExecution: false,
  stdoutByteLimit: 262144,
  stderrByteLimit: 262144,
  combinedOutputByteLimit: 393216,
  resultByteLimit: 4096,
} as const
